## 모듈과 패키지

In [86]:
# 모듈은 변수, 함수, 클래스를 담고 있는 파일 (.py)
# 패키지는 여러 모듈을 묶은 것 (폴더)
# import 모듈
# import 모듈1, 모듈2
# 모듈.변수
# 모듈.함수()
# 모듈.클래스()

In [87]:
import math # math라는 모듈이 있어요
print(math.pi)
print(math.sqrt(4)) # sqrt는 제곱근 구해줌

3.141592653589793
2.0


In [88]:
import math as m # math를 가져오는 데 m 이라는 이름으로 가져온다
print(m.pi)
print(m.sqrt(4))

3.141592653589793
2.0


In [89]:
from math import pi, sqrt
print(pi) # math.pi 는 오히려 안됨
print(sqrt(4))

3.141592653589793
2.0


In [90]:
from math import * # * 이 all 이란 뜻
print(pi)
print(sqrt(4))
print(sin(pi))

3.141592653589793
2.0
1.2246467991473532e-16


In [91]:
from math import sqrt as s
print(s(4))

2.0


In [92]:
from math import sqrt as s, pi as p
print(p)
print(s(4))

3.141592653589793
2.0


In [93]:
# import 패키지
# import 패키지.모듈1
# import 패키지.모듈1, 패키지.모듈2
# 패키지.모듈.변수
# 패키지.모듈.함수()
# 패키지.모듈.클래스()

In [94]:
import numpy as np # numpy는 라이브러리(패키지와 모듈들을 모아놓음)다 (numerical python)
a=np.array([1,2,3])
a

array([1, 2, 3])

In [95]:
import numpy.random
numpy.random.randn(3,3) # Normal distribution, (3,3)은 3행 3열 짜리를 의미

array([[-0.63477818,  1.41650372,  1.9839991 ],
       [-0.82676949,  1.81018045, -0.44376709],
       [-0.71608462, -0.36030105, -0.06842194]])

In [96]:
import numpy.random as nr
nr.randn(3,3)

array([[ 0.67872898,  0.52440577, -0.56758787],
       [ 1.45929164,  0.69167305, -1.03409693],
       [ 1.65912344, -0.04222724,  1.96006857]])

In [97]:
from numpy.random import randn
randn(3,3)

array([[ 0.19578135,  0.58151842,  0.05392976],
       [ 1.23209285,  1.05874596,  0.43639479],
       [-0.92042209, -0.76872057,  0.70800107]])

In [98]:
from numpy.random import *
rand(3,3) # uniform distribution

array([[0.56606092, 0.10110929, 0.22195706],
       [0.65620925, 0.63984877, 0.35326695],
       [0.51446103, 0.20049035, 0.39916601]])

In [99]:
from numpy.random import randn as rn
rn(3,3)

array([[ 2.48515951, -0.0101712 ,  0.58082915],
       [-1.23634034, -0.69542531, -0.53599433],
       [-0.96231952, -1.28096103,  0.12860562]])

In [100]:
from numpy.random import randn as rn, rand as r
print(rn(3,3))
print(r(3,3))

[[ 2.09257895  1.27455925 -0.63790374]
 [ 0.32901192 -0.35297909 -1.41798282]
 [ 1.11899549 -0.89050578  0.54765141]]
[[0.87033128 0.5022825  0.61644399]
 [0.83743914 0.81581593 0.59232369]
 [0.31647508 0.8923088  0.64531701]]


## numpy 본격적으로

In [101]:
import numpy as np
a=np.array([1,2,3,4]) # list가 입력으로 들어가는 함수
print(a)
print(type(a))
print(a.dtype) # data type
print(a.shape)
b=np.array([1,2,3.1,4])
print(b.dtype) # 하나라도 실수면 자동으로 실수 타입으로
print(b)

[1 2 3 4]
<class 'numpy.ndarray'>
int64
(4,)
float64
[1.  2.  3.1 4. ]


In [102]:
A=np.array([[1,2,3],[3,4,5]]) # 이 셀부터는 import numpy as np 는 실행 했다 치고 작성
# A=np.array([[1,2],[3,4,5]]) # 리스트와는 달리 이제는 행렬이라서 각 행에 해당하는 숫자의 개수가 같아야 함
print(A)
print(A.shape)
print(A.ndim) # 차원의 수
print(A.size) # 전체 성분의 수

[[1 2 3]
 [3 4 5]]
(2, 3)
2
6


In [103]:
print(np.zeros(5))
print(np.zeros_like(A))
print(np.ones(5))
print(np.zeros((3,3))) # 튜플을 입력으로! 그냥 np.zeros(3,3)은 안돼요
print(np.arange(3,10,2)) # range랑 같은데 array로 만들어줌
print(np.arange(0,1,0.1)) # 소수점 가능
print(np.linspace(0,1,10, endpoint=False)) # 0 에서부터 1 포함(default) 10개로

[0. 0. 0. 0. 0.]
[[0 0 0]
 [0 0 0]]
[1. 1. 1. 1. 1.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[3 5 7 9]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [104]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=a+b
print(c) # 드디어! 양 옆으로 길어지는 게 아닌 벡터의 합이 나옴!

[5 7 9]


In [105]:
A=np.array([[1,2,3],[1,2,3]])
B=np.array([[4,5,6],[1,1,1]])
C=A+B
D=A-B
print(C)
print(D)
print()
print(A*B) # 곱셈은? 성분끼리의 곱! (Hadamard product)
print(A/B) # 나누기도 마찬가지
print(B**2) # 제곱도 각 성분에 대해서 해준다

[[5 7 9]
 [2 3 4]]
[[-3 -3 -3]
 [ 0  1  2]]

[[ 4 10 18]
 [ 1  2  3]]
[[0.25 0.4  0.5 ]
 [1.   2.   3.  ]]
[[16 25 36]
 [ 1  1  1]]


In [106]:
A=np.array([[1,2],[3,4]])
B=np.array([[1,2],[3,4]])
print(A*B)
print(A@B) # 이게 진짜 행렬 곱하기

[[ 1  4]
 [ 9 16]]
[[ 7 10]
 [15 22]]


## numpy 의 인덱싱과 슬라이싱

In [107]:
a=np.array([1,2,3,4,5,6,7,8,9])
# 인덱싱과 슬라이싱, list할 때와 동일!
print(a[0])
print(a[1])
print(a[-1])
print(a[1:4])
print(a[7:])
print(a[:7])
print(a[:])

1
2
9
[2 3 4]
[8 9]
[1 2 3 4 5 6 7]
[1 2 3 4 5 6 7 8 9]


In [108]:
# 행렬에 대한 인덱싱과 슬라이싱
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A[0]) # 하나만 쓰면 행에 대한 인덱싱 (리스트 속 리스트 생각)
print(A[-1])
print(A[1:])
print(A[:])
print(A[0][2])
print(A[0,2]) # 2차원 행렬도 동일한데, 리스트와 달리 이런 것도 됨
B=[[1,2,3,4], [5,6,7,8]]
print(B)
print(B[0][2])
# print(B[0,2]) # error!
print(A[1,:]) # 1 행, 전부
print(A[1,0:3:2])
print(A[:,2]) # 전부, 2 열

[1 2 3]
[7 8 9]
[[4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
3
3
[[1, 2, 3, 4], [5, 6, 7, 8]]
3
[4 5 6]
[4 6]
[3 6 9]


In [109]:
# 3차원 행렬 인덱싱
A=np.array([ [[0,1,2,3],[4,5,6,7],[8,9,10,11]] ,
             [[12,13,14,15],[16,17,18,19],[20,21,22,23]] ])
print(A)
print(A.shape)
print(A[0,1,2])

a=np.array([[[1,2,3,4]]]) # 대괄호가 하나 늘어나면 왼쪽에 shape 값이 추가 된다.
print(a.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)
6
(1, 1, 4)


In [110]:
# boolean 인덱싱
a=[1,2,3,4,5,3,3]
print(a==3) # 여러개 값 들어있는 리스트랑 3 달랑 하나랑 같냐? 다르다!
A=np.array([[1,2,3,4],[5,3,7,3]])
print(A==3) # 리스트와 달리 각 성분에 대해 비교해줌
print(A[A==3]) # True, False가 담긴 행렬로 인덱싱 가능!!

A[A>3] = 100
print(A) # 그러면 이런 것도 가능하다! (3보다 큰 애들을 100으로 바꿔줘)

A=np.array([[1,2],[3,4],[5,6],[7,8]])
B=np.array([True, False, False, True]) # 참고로 그냥 리스트여도 됨
print(A[B,:]) # 0행, 3행 슬라이싱

b=np.array([1,2,3,4])
print(b[[True,True,False,False]])
c=[1,2,3,4]
# c[[True,True,False,False]] # error!

False
[[False False  True False]
 [False  True False  True]]
[3 3 3]
[[  1   2   3 100]
 [100   3 100   3]]
[[1 2]
 [7 8]]
[1 2]


In [111]:
# array로 인덱싱
a=np.array([1,2,3,4,5])
A=a[2]
print(A)
A=a[ np.array(2) ] # np.array를 안에다가?
print(A)
A=a[ np.array([2,3,4]) ]
print(A)
A=a[ np.array([[2,2,2],[3,3,3]]) ]
print(A) # 인덱싱된 애들로 2행 3열짜리 행렬을 만든다

a=[1,2,3]
# a[ [1,1,1,1,2,2,2] ] # error!

a=np.array([[1,2,3],[4,5,6]])
print(a[0])
A=a[ np.array([[0,1],[1,1]]) ]
print(A.shape) # 예를 들어, a[0] = array([1,2,3])과 같이 1차원 데이터이므로 한 차원이 뒤에 늘어나서 2,2, "3" 이 된다!
print(A) # segmentation 결과 그림 보여줄 때 사용!

3
3
[3 4 5]
[[3 3 3]
 [4 4 4]]
[1 2 3]
(2, 2, 3)
[[[1 2 3]
  [4 5 6]]

 [[4 5 6]
  [4 5 6]]]


In [112]:
A=np.array([[1,2],[3,4],[5,6],[7,8]])
print(A)
print(A.shape)

# 1. A[몇 번째 행이냐, 몇 번째 열이냐]
print(A[0,1])
# 2. A[ array(bool) ] => A와 같은 shape을 가지는 array형 bool이 어디에 True를 가지고 있냐
print(A[ np.array([[False,True],[False,False],[False,False],[False,False]]) ])
print(A[A==2])
# 3. A[몇 번째 값에 True가 있냐, 몇 번째 값에 True가 있냐]
print(A[ [True,False,False,False], [False,True] ])
# 4. A[ array ] # 몇 번째 것을 어떻게 쌓을거냐
print(A[ np.array([1,1,2,2,2]) ])

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(4, 2)
2
[2]
[2]
[2]
[[3 4]
 [3 4]
 [5 6]
 [5 6]
 [5 6]]


## numpy의 여러 함수들

In [113]:
A=np.random.randn(3,3) # 여긴 튜플로 안줘도 됨
B=np.random.rand(3,3)
print(A)
print(B)
print(A[A[:,0]<0,:]) # 0 번째 열이 음수인 행들 # 내 필기용

[[-0.02493801 -0.48889941 -0.91030058]
 [-1.53433257  0.18393941 -0.2165678 ]
 [ 0.69429408  1.06277725 -0.00293355]]
[[0.98226891 0.08641054 0.02281826]
 [0.29598718 0.97401854 0.4905183 ]
 [0.06346977 0.53475607 0.67314123]]
[[-0.02493801 -0.48889941 -0.91030058]
 [-1.53433257  0.18393941 -0.2165678 ]]


In [114]:
A=np.random.randn(3,3)
print(A)
print(np.abs(A))
print(np.sqrt(np.abs(A)))
print(np.exp(A))
print(np.log(np.abs(A)))
print(np.log(np.exp(1))) # np.exp(1) = e^1
print(np.log10(10))
print(np.log2(2))
print(np.round(A)) # 반올림
print(np.round(A,2)) # 소수점 둘째자리까지
print(np.floor(A)) # 내림
print(np.ceil(A)) # 올림

[[-1.06451226 -1.54940654  0.200761  ]
 [ 0.59149842  2.18344192  0.48701605]
 [-0.19359979 -0.29722002 -1.10524479]]
[[1.06451226 1.54940654 0.200761  ]
 [0.59149842 2.18344192 0.48701605]
 [0.19359979 0.29722002 1.10524479]]
[[1.03175204 1.2447516  0.44806361]
 [0.76908935 1.47764743 0.69786535]
 [0.43999977 0.54517888 1.05130623]]
[[0.34489603 0.21237397 1.2223326 ]
 [1.80669358 8.87680698 1.62745273]
 [0.8239876  0.74288055 0.33112982]]
[[ 0.06251673  0.43787198 -1.60564015]
 [-0.52509626  0.78090249 -0.7194582 ]
 [-1.64196216 -1.21328262  0.10006684]]
1.0
1.0
1.0
[[-1. -2.  0.]
 [ 1.  2.  0.]
 [-0. -0. -1.]]
[[-1.06 -1.55  0.2 ]
 [ 0.59  2.18  0.49]
 [-0.19 -0.3  -1.11]]
[[-2. -2.  0.]
 [ 0.  2.  0.]
 [-1. -1. -2.]]
[[-1. -1.  1.]
 [ 1.  3.  1.]
 [-0. -0. -1.]]


In [115]:
print(np.sin(np.pi/6))
print(np.cos(np.pi/3))
print(np.tan(np.pi/4))
print(np.tanh(-10))

0.49999999999999994
0.5000000000000001
0.9999999999999999
-0.9999999958776927


In [116]:
np.nan # not a number
# np.log(-1)
print(np.isnan([1,2,np.nan,3,4]))
print(np.isinf([1,2,3,4,np.inf]))

[False False  True False False]
[False False False False  True]


In [117]:
A=np.random.randn(3,4)
print(A)
print(np.max(A))
print(np.max(A,axis=0))
print(np.max(A,axis=1)) # 1D array로 바꿔버림
print(np.max(A,axis=0, keepdims=True))
print(np.max(A,axis=1, keepdims=True)) # 3 행 1열 짜리 2D array
print(np.min(A))
print(np.min(A,axis=0))
print(np.min(A,axis=1))
print(np.argmax(A))
print(np.argmax(A,axis=0)) # 각 열에서 가장 큰 애가 존재하는 인덱스
print(np.argmax(A,axis=1)) # 각 행에서 가장 큰 애가 존재하는 인덱스

[[-2.13886838 -0.73885082  0.33459537  0.51942006]
 [ 2.37122969  0.42117713 -0.02490533 -1.1677918 ]
 [-2.52152143  0.95949782 -0.24421484 -0.70381606]]
2.371229693534399
[2.37122969 0.95949782 0.33459537 0.51942006]
[0.51942006 2.37122969 0.95949782]
[[2.37122969 0.95949782 0.33459537 0.51942006]]
[[0.51942006]
 [2.37122969]
 [0.95949782]]
-2.5215214315033174
[-2.52152143 -0.73885082 -0.24421484 -1.1677918 ]
[-2.13886838 -1.1677918  -2.52152143]
4
[1 2 0 0]
[3 0 1]


In [118]:
a=np.random.randn(6,1)
print(a)
a_sorted=np.sort(a,axis=0)
print(a_sorted)
print(np.flipud(a_sorted))

a=np.random.randn(6,1)
print(a)
print(a.sort(axis=0))

print(np.max(a))
print(a.max())

[[ 0.24519261]
 [ 2.45104468]
 [ 0.40785502]
 [-0.0694186 ]
 [-0.52674347]
 [-0.05188733]]
[[-0.52674347]
 [-0.0694186 ]
 [-0.05188733]
 [ 0.24519261]
 [ 0.40785502]
 [ 2.45104468]]
[[ 2.45104468]
 [ 0.40785502]
 [ 0.24519261]
 [-0.05188733]
 [-0.0694186 ]
 [-0.52674347]]
[[-1.74922111]
 [-0.37958866]
 [ 0.39220304]
 [-0.83061122]
 [-0.06924296]
 [ 1.01465617]]
None
1.0146561733016792
1.0146561733016792


In [119]:
A=np.random.randn(3,4)
print(A)
print(np.sum(A))
print(np.sum(A,axis=1))
print(np.sum(A,axis=1,keepdims=True))
print(np.mean(A))
print(np.mean(A,axis=1))
print(np.mean(A,axis=1,keepdims=True))
print(np.std(A)) # standard deviation 표준 편차

print(A.sum(axis=1, keepdims=True))
print(A.mean(axis=1, keepdims=True))
print(A.std())

[[ 0.66793929 -0.01431598 -0.56584122 -0.35691687]
 [ 0.44033464 -1.03815422  0.12612038 -0.44763595]
 [ 1.80703314 -0.37322424 -1.58501138  0.31373601]]
-1.0259363972388365
[-0.26913478 -0.91933514  0.16253353]
[[-0.26913478]
 [-0.91933514]
 [ 0.16253353]]
-0.08549469976990304
[-0.0672837  -0.22983379  0.04063338]
[[-0.0672837 ]
 [-0.22983379]
 [ 0.04063338]]
0.8321408745422826
[[-0.26913478]
 [-0.91933514]
 [ 0.16253353]]
[[-0.0672837 ]
 [-0.22983379]
 [ 0.04063338]]
0.8321408745422826


In [120]:
A=np.random.randint(1,5,size=(12,)) # 1부터 5미만 12개 정수 (1 차원은 (N,) 과 같이 표현)
print(A)
print(A.shape)

B=A.reshape(2,2,3)
print(B)
print(B.ndim) # 3 차원 행렬이다

[1 2 4 1 4 1 2 4 2 3 2 4]
(12,)
[[[1 2 4]
  [1 4 1]]

 [[2 4 2]
  [3 2 4]]]
3


In [121]:
a=np.array([1,2,3])
b=np.array([2,2,1])
print(np.sum(a*b))

a=a.reshape(3,1)
b=b.reshape(3,1)
print(a.transpose()@b)
print(a.T@b)

A=np.random.randn(4,3,6)
print(A.transpose(0,2,1).shape)

9
[[9]]
[[9]]
(4, 6, 3)


In [122]:
A=np.arange(20)
print(A)
print(A.reshape(4,5))
print(A.reshape(4,-1).shape) # 4개 행이 될 수 있도록 열의 수를 맞춰라
print(A.reshape(2,5,-1).shape)
print(A.reshape(2,-1,5).shape)
print(A.reshape(1,-1).shape) # 2차원 행 벡터
print(A.reshape(-1,1).shape) # 2차원 열 벡터

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
(4, 5)
(2, 5, 2)
(2, 2, 5)
(1, 20)
(20, 1)


In [123]:
x=np.random.randn(2,3,4,5,6)
print(x[1,2,:,:,:].shape)
print(x[1,2,...].shape) # x[1, 2, …] 는 x[1, 2, :, :, :] 와 같습니다.
print(x[:,:,:,:,3].shape)
print(x[...,3].shape) # x[…, 3] 는 x[:, :, :, :, 3] 와 같습니다.
print(x[1,:,:,3,:].shape)
print(x[1,...,3,:].shape) # x[1, …, 3, :] 는 x[1, :, :, 3, :] 와 같습니다.

(4, 5, 6)
(4, 5, 6)
(2, 3, 4, 5)
(2, 3, 4, 5)
(3, 4, 6)
(3, 4, 6)


In [124]:
A=np.ones((3,4))
B=np.zeros((3,4))
C=np.vstack([A,B])
D=np.hstack([A,B])
E=np.block([[A],[B]])
F=np.block([A,B])
G=np.block([ [[A]], [[B]] ])

print(C)
print(D)
print(E)
print(F)
print(G)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0. 0. 0.]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [125]:
A = np.random.randn(1,1,1,3,1,1,4,1)
# print(A)
print(A.shape)
print(A.squeeze().shape)
print(A.squeeze(axis=(0,2,4,5)).shape)

(1, 1, 1, 3, 1, 1, 4, 1)
(3, 4)
(1, 3, 4, 1)


In [126]:
A = np.random.randn(3,4)
A1 = A[np.newaxis,...] # np.newaxis is None <- True
print(A1.shape)
A2 = A[...,np.newaxis]
print(A2.shape)
A3 = A[:,np.newaxis,:]
print(A3.shape)
A1 = np.expand_dims(A,axis=0)
print(A1.shape)
A2 = np.expand_dims(A,axis=2)
print(A2.shape)
A3 = np.expand_dims(A,axis=1)
print(A3.shape)
A1 = A.reshape(1,3,4)
print(A1.shape)
A2 = A.reshape(3,4,1)
print(A2.shape)
A3 = A.reshape(3,1,4)
print(A3.shape)

(1, 3, 4)
(3, 4, 1)
(3, 1, 4)
(1, 3, 4)
(3, 4, 1)
(3, 1, 4)
(1, 3, 4)
(3, 4, 1)
(3, 1, 4)
